#######################################################################################
# Book settings
title : Scientific Python QuickStart
author: Thomas J. Sargent and John Stachurski


# Information about where the book exists on the web
description: >-
  A brief introduction to Python programming for scientific applications.

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : "force"
